LOAD DATA
INFILE 'Advertisers_edited.dat'  "str '\n'"
INSERT INTO TABLE Advertisers
REENABLE DISABLED_CONSTRAINTS
FIELDS TERMINATED BY "\t" 
(
ADVERTISERID,
BUDGET,
CTC,
G_1_BALANCE,
G_2_BALANCE,
B_1_BALANCE,
B_2_BALANCE,
GEN_1_BALANCE,
GEN_2_BALANCE,
G_1_COUNT,
G_2_COUNT,
B_1_COUNT,
B_2_COUNT,
GEN_1_COUNT,
GEN_2_COUNT
)